In [1]:
from google import genai
from google.genai import types
import base64
import asyncio

In [ ]:
import time, json
import re, logging
import os
import tqdm

## Prompt Experiment

In [24]:
text_prompt = """
Objective:

Identify a 5-second time range within the provided video clip that best meets the following conditions, and provide a score for each condition, as well as a total score. The selected range must feature a **single individual**. The face must belong to the **same person** throughout the entire 5-second duration. Any switch to a different person's face is unacceptable. The person's facial features (e.g., hair, skin tone, face shape) must remain **consistent** throughout the selected range. The person's face should maintain a relatively **consistent angle** towards the camera. Significant changes in head orientation are not acceptable.

Conditions:

Speaking: The person must be speaking clearly and audibly.
Immobility: The person must be either sitting or standing completely still. Any visible movement, including but not limited to head nods, shakes, fidgeting, or shifting weight, is unacceptable. The person's posture should remain virtually unchanged throughout the selected range.
Unobstructed Mouth: When the person is speaking, their mouth must be 100% unobstructed. No part of any object (including hands, clothing, microphones, or text overlays) can be in front of the mouth at any time during speech. The mouth must be clearly and fully visible for the entire 5-second duration.
Appropriate Face Angle: The person's face should be angled towards the camera, allowing for a clear view of their features.
Good Face Lighting: The person's face should be well-lit and easily visible.
Clean Background: The background should be relatively uncluttered and free of distractions.
Consistent Lighting: The lighting must be stable, with no noticeable flickering or abrupt changes in brightness. Gradual changes in background lighting (e.g., clouds passing in front of the sun) are acceptable, but any sudden or significant change in the overall brightness of the person's face is unacceptable.
Appropriate Person Size: The person's face should occupy a reasonable portion of the frame, neither too small nor too large.

Scoring System (for each 5-second range):

For each condition, assign a score from 0 to 10, where:

10 = Perfectly meets the condition.
5 = Partially meets the condition.
0 = Does not meet the condition at all.

Selection Process Steps:

1. Review the entire video clip.
2. **Randomly determine the order in which you will evaluate the following criteria: Face Angle, Background Cleanliness, Person Size, Person Movement, Face Lighting, and Unobstructed Mouth.** This randomization is crucial to minimize bias.
3. **Mitigating the Risk of Missing Mouth Obstructions:** To ensure the "Unobstructed Mouth" condition is strictly met, use the following techniques:
    - Review the video frame-by-frame: This is the most accurate method, but also the most time-consuming.
    - Slow down the playback speed: This makes it easier to catch quick movements.
    - Utilize video analysis software (if available): Some software can automatically detect objects (like hands) and track their movement, making it easier to identify potential obstructions.
    - Consider multiple reviewers: Different people may notice different things.
4. For each criterion, re-watch the video clip and focus specifically on that criterion.
5. Assign a score from 0 to 10 for each criterion.
6. Calculate a total score by summing the scores for all criteria.
7. Select the 5-second time range with the highest total score. If no range meets all conditions, indicate "No suitable range found."

Your response should be a JSON string with the following structure:
{
 "start_time": [Start Time in seconds],
 "end_time": [End Time in seconds],
 "face_angle_score": [Score],
 "background_cleanliness_score": [Score],
 "person_size_score": [Score],
 "person_movement_score": [Score],
 "face_lighting_score": [Score],
 "unobstructed_mouth_score": [Score],
 "total_score": [Total Score],
 "suitable_range_found": [true/false]
}

Example Output (with a suitable range found):
{
 "start_time": 15,
 "end_time": 20,
 "face_angle_score": 8,
 "background_cleanliness_score": 8,
 "person_size_score": 7,
 "person_movement_score": 10,
 "face_lighting_score": 8,
 "unobstructed_mouth_score": 10,
 "total_score": 51,
 "suitable_range_found": true
}

Example Output (if no suitable range is found):
{
 "start_time": null,
 "end_time": null,
 "face_angle_score": null,
 "background_cleanliness_score": null,
 "person_size_score": null,
 "person_movement_score": null,
 "face_lighting_score": null,
 "unobstructed_mouth_score": null,
 "total_score": null,
 "suitable_range_found": false
}

Return the JSON string as specified in the instructions and include any additional text, explanations, or justifications.
Let's start to analyze the video following the Selection Process Steps above step by step.
"""

In [45]:
# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

In [ ]:
class VisualDeepfakeDetector:
    def __init__(self, prompt, model="gemini-2.0-flash-001"): #settings
        # self.logger = utils.get_logger()
        self.model = model
        # generation config
        self.generate_content_config = types.GenerateContentConfig(
            temperature = 0.1,
            top_p = 0.95,
            max_output_tokens = 8192,
            response_modalities = ["TEXT"],
            safety_settings = [types.SafetySetting(
              category="HARM_CATEGORY_HATE_SPEECH",
              threshold="OFF"
            ),types.SafetySetting(
              category="HARM_CATEGORY_DANGEROUS_CONTENT",
              threshold="OFF"
            ),types.SafetySetting(
              category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
              threshold="OFF"
            ),types.SafetySetting(
              category="HARM_CATEGORY_HARASSMENT",
              threshold="OFF"
            )],
        )
        self.client = genai.Client(
            vertexai=True,
            project="deepfake-422901",
            location="us-east1",
        )
        self.prompt = prompt
    
    def extract_json_text(self, text):
        """Extracts JSON from a text string using regular expressions."""
        try:
            json_match = re.search(r"\{.*\}", text, re.DOTALL)  # Find JSON block
            if json_match:
                return json_match.group(0)
            else:
                logger.warning("No JSON found in text.")
                return None
        except Exception as e:
            logger.exception("Error extracting JSON.")
            return None
    
    def generate(self, video_path, max_retries=3, initial_delay=1):
        """Generates content using the Gemini API with retries and logging."""
        retries = 0
        success_flag = False
        api_params = {  # Log API parameters
            "model": self.model,
            "temperature": self.generate_content_config.temperature,
            "top_p": self.generate_content_config.top_p,
            "max_output_tokens": self.generate_content_config.max_output_tokens,
            "safety_settings": self.generate_content_config.safety_settings
        }

        try:
            with open(video_path, "rb") as f:
                video_data = f.read()
            video_part = types.Part.from_bytes(mime_type="video/mp4", data=video_data)
            contents = [
                types.Content(
                    role="user",
                    parts=[
                        types.Part.from_text(text=self.prompt),
                        video_part
                    ]
                )
            ]

            while retries <= max_retries and not success_flag:
                try:
                    logger.info(f"Attempting API call (retry {retries}/{max_retries}). API Parameters: {api_params}")
                    complete_text = ""
                    for chunk in self.client.models.generate_content_stream(
                        model=self.model,
                        contents=contents,
                        config=self.generate_content_config,
                    ):
                        complete_text += chunk.text

                    logger.debug(f"Raw API Response: {complete_text}")  # Log raw response

                    clean_text = self.extract_json_text(complete_text)
                    if not clean_text:
                        raise ValueError("Could not extract JSON from API response.")

                    logger.debug(f"Extracted JSON: {clean_text}")

                    try:
                        json_response = json.loads(clean_text)
                        success_flag = True
                        return json_response
                    except json.JSONDecodeError as e:
                        logger.exception("Error decoding JSON.")
                        raise  # Re-raise for retry logic

                except Exception as e:  # Catch specific API exceptions
                    retries += 1
                    if retries <= max_retries:
                        delay = initial_delay * (2 ** (retries - 1))  # Exponential backoff
                        logger.warning(f"An error occurred: {e}. Retrying in {delay} seconds...")
                        time.sleep(delay)
                    else:
                        logger.error(f"Maximum retries ({max_retries}) exceeded. Giving up.")
                        raise

        except FileNotFoundError:
            logger.error(f"Video file not found: {video_path}")
            raise
        except Exception as e:
            logger.exception("Unexpected error during API call.")
            raise

    def run(self, video_path):
        try:
            res = self.generate(video_path)
            return res
        except Exception as e:
            logger.error(f"Error during run: {e}")
            return None

In [18]:
detector = VisualDeepfakeDetector(prompt=text_prompt, model="gemini-2.0-flash-001")

In [54]:
safe_video_target_time = {}

safe_video_path = "./data/datasets/DemoDataset/videos/safe_videos"
for video_type in tqdm.tqdm(os.listdir(safe_video_path)):
    if video_type in safe_vedio_exp_cat: # sample portion for exp
        print(video_type)
        video_type_path = os.path.join(safe_video_path, video_type)
        for video in tqdm.tqdm(os.listdir(video_type_path)):
            print('Start process:', video)
            video_path = os.path.join(video_type_path, video)
            res = detector.run(video_path)
            safe_video_target_time.setdefault('video', []).append(video)
            safe_video_target_time.setdefault('label', []).append('safe')
            safe_video_target_time.setdefault('start_time', []).append(res['start_time'])
            safe_video_target_time.setdefault('end_time', []).append(res['end_time'])

  0%|          | 0/19 [00:00<?, ?it/s]

investment

  0%|          | 0/54 [00:00<?, ?it/s]2025-04-08 09:52:35,359 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:52:35,360 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:52:35,360 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_025.mp4

2025-04-08 09:52:38,332 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  2%|▏         | 1/54 [00:08<07:27,  8.45s/it]2025-04-08 09:52:43,812 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:52:43,812 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:52:43,813 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_023.mp4

2025-04-08 09:52:47,616 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  4%|▎         | 2/54 [00:14<06:16,  7.24s/it]2025-04-08 09:52:50,211 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:52:50,212 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:52:50,213 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_011.mp4

2025-04-08 09:52:52,579 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  6%|▌         | 3/54 [00:19<05:09,  6.07s/it]2025-04-08 09:52:54,888 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:52:54,888 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:52:54,889 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_007.mp4

2025-04-08 09:53:02,522 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  7%|▋         | 4/54 [00:28<06:07,  7.34s/it]2025-04-08 09:53:04,172 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:53:04,173 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:53:04,174 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_046.MP4

2025-04-08 09:53:06,282 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
2025-04-08 09:53:41,546 - WARNING - No JSON found in text.
2025-04-08 09:53:41,547 - WARNING - An error occurred: Could not extract JSON from API response.. Retrying in 1 seconds...
2025-04-08 09:53:42,549 - INFO - Attempting API call (retry 1/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:53:42,550 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:53:42,550 - INFO - AFC remote call 1 is done.
2025-04-08 09:53:44,563 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  9%|▉         | 5/54 [01:11<16:25, 20.12s/it]2025-04-08 09:53:46,944 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:53:46,945 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:53:46,945 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_021.mp4

2025-04-08 09:53:49,672 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 11%|█         | 6/54 [01:19<12:47, 15.98s/it]2025-04-08 09:53:54,902 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:53:54,902 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:53:54,903 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_044.MP4

2025-04-08 09:54:02,235 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 13%|█▎        | 7/54 [01:28<10:40, 13.62s/it]2025-04-08 09:54:03,663 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:03,664 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:03,664 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_030.mp4

2025-04-08 09:54:07,482 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 15%|█▍        | 8/54 [01:34<08:40, 11.32s/it]2025-04-08 09:54:10,047 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:10,048 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:10,048 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_008.mp4

2025-04-08 09:54:14,645 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 17%|█▋        | 9/54 [01:41<07:29,  9.99s/it]2025-04-08 09:54:17,133 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:17,134 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:17,134 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_019.mp4

2025-04-08 09:54:24,260 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 19%|█▊        | 10/54 [01:50<06:57,  9.48s/it]2025-04-08 09:54:25,459 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:25,460 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:25,460 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_012.mp4

2025-04-08 09:54:28,052 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 20%|██        | 11/54 [01:54<05:42,  7.97s/it]2025-04-08 09:54:30,016 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:30,017 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:30,017 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_001.mp4

2025-04-08 09:54:35,444 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 22%|██▏       | 12/54 [02:01<05:19,  7.61s/it]2025-04-08 09:54:36,806 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:36,806 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:36,807 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_039.mp4

2025-04-08 09:54:39,648 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 24%|██▍       | 13/54 [02:06<04:44,  6.95s/it]2025-04-08 09:54:42,230 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:42,230 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:42,231 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_041.mp4

2025-04-08 09:54:47,105 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 26%|██▌       | 14/54 [02:13<04:38,  6.97s/it]2025-04-08 09:54:49,253 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:49,254 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:49,254 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_048.MP4

2025-04-08 09:54:52,387 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 28%|██▊       | 15/54 [02:19<04:16,  6.57s/it]2025-04-08 09:54:54,905 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:54:54,906 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:54:54,906 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_047.MP4

2025-04-08 09:54:58,441 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 30%|██▉       | 16/54 [02:25<04:02,  6.38s/it]2025-04-08 09:55:00,828 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:00,828 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:00,829 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_032.mp4

2025-04-08 09:55:04,536 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 31%|███▏      | 17/54 [02:30<03:43,  6.05s/it]2025-04-08 09:55:06,109 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:06,109 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:06,110 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_014.mp4

2025-04-08 09:55:09,948 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 33%|███▎      | 18/54 [02:37<03:50,  6.41s/it]2025-04-08 09:55:13,357 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:13,358 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:13,358 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_050.MP4

2025-04-08 09:55:16,091 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 35%|███▌      | 19/54 [02:43<03:37,  6.20s/it]2025-04-08 09:55:19,082 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:19,082 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:19,083 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_002.mp4

2025-04-08 09:55:21,936 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 37%|███▋      | 20/54 [02:50<03:32,  6.24s/it]2025-04-08 09:55:25,406 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:25,407 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:25,407 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_049.MP4

2025-04-08 09:55:27,409 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 39%|███▉      | 21/54 [02:55<03:19,  6.04s/it]2025-04-08 09:55:30,970 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:30,971 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:30,971 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_015.mp4

2025-04-08 09:55:38,300 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 41%|████      | 22/54 [03:04<03:39,  6.85s/it]2025-04-08 09:55:39,725 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:39,725 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:39,726 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_003.mp4

2025-04-08 09:55:42,972 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 43%|████▎     | 23/54 [03:09<03:20,  6.45s/it]2025-04-08 09:55:45,251 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:45,251 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:45,252 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_026.mp4

2025-04-08 09:55:48,472 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 44%|████▍     | 24/54 [03:15<03:05,  6.19s/it]2025-04-08 09:55:50,827 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:50,827 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:50,828 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_040.mp4

2025-04-08 09:55:53,160 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 46%|████▋     | 25/54 [03:20<02:51,  5.93s/it]2025-04-08 09:55:56,137 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:55:56,138 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:55:56,138 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_043.MP4

2025-04-08 09:56:07,402 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 48%|████▊     | 26/54 [03:33<03:44,  8.03s/it]2025-04-08 09:56:09,086 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:09,087 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:09,087 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_036.mp4

2025-04-08 09:56:11,849 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 50%|█████     | 27/54 [03:41<03:38,  8.09s/it]2025-04-08 09:56:17,296 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:17,296 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:17,297 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_033.mp4

2025-04-08 09:56:20,563 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 52%|█████▏    | 28/54 [03:47<03:12,  7.41s/it]2025-04-08 09:56:23,135 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:23,136 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:23,136 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_031.mp4

2025-04-08 09:56:27,771 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 54%|█████▎    | 29/54 [03:54<02:59,  7.17s/it]2025-04-08 09:56:29,747 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:29,748 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:29,748 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_022.mp4

2025-04-08 09:56:32,699 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 56%|█████▌    | 30/54 [04:00<02:42,  6.79s/it]2025-04-08 09:56:35,652 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:35,653 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:35,653 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_018.mp4

2025-04-08 09:56:40,300 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 57%|█████▋    | 31/54 [04:07<02:38,  6.89s/it]2025-04-08 09:56:42,770 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:42,770 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:42,771 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_028.mp4

2025-04-08 09:56:45,527 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 59%|█████▉    | 32/54 [04:12<02:21,  6.44s/it]2025-04-08 09:56:48,168 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:48,169 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:48,169 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_010.mp4

2025-04-08 09:56:50,597 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 61%|██████    | 33/54 [04:17<02:05,  5.96s/it]2025-04-08 09:56:52,995 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:52,995 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:52,996 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_053.mp4

2025-04-08 09:56:55,597 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 63%|██████▎   | 34/54 [04:22<01:51,  5.59s/it]2025-04-08 09:56:57,719 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:56:57,719 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:56:57,720 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_027.mp4

2025-04-08 09:57:01,073 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 65%|██████▍   | 35/54 [04:36<02:32,  8.03s/it]2025-04-08 09:57:11,450 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:11,450 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:11,451 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_005.mp4

2025-04-08 09:57:13,976 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 67%|██████▋   | 36/54 [04:41<02:09,  7.17s/it]2025-04-08 09:57:16,624 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:16,624 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:16,625 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_045.MP4

2025-04-08 09:57:21,341 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 69%|██████▊   | 37/54 [04:48<02:00,  7.06s/it]2025-04-08 09:57:23,429 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:23,429 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:23,430 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_035.mp4

2025-04-08 09:57:27,132 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 70%|███████   | 38/54 [04:54<01:47,  6.73s/it]2025-04-08 09:57:29,392 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:29,393 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:29,393 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_051.MP4

2025-04-08 09:57:32,319 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 72%|███████▏  | 39/54 [04:59<01:33,  6.24s/it]2025-04-08 09:57:34,485 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:34,485 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:34,486 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_006.mp4

2025-04-08 09:57:37,424 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 74%|███████▍  | 40/54 [05:04<01:23,  5.94s/it]2025-04-08 09:57:39,706 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:39,706 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:39,707 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_020.mp4

2025-04-08 09:57:42,185 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 76%|███████▌  | 41/54 [05:09<01:12,  5.55s/it]2025-04-08 09:57:44,371 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:44,372 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:44,372 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_034.mp4

2025-04-08 09:57:48,186 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 78%|███████▊  | 42/54 [05:15<01:10,  5.85s/it]2025-04-08 09:57:50,928 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:50,929 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:50,930 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_017.mp4

2025-04-08 09:57:53,967 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 80%|███████▉  | 43/54 [05:21<01:05,  5.92s/it]2025-04-08 09:57:56,986 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:57:56,986 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:57:56,987 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_038.mp4

2025-04-08 09:58:08,512 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 81%|████████▏ | 44/54 [05:34<01:20,  8.05s/it]2025-04-08 09:58:10,011 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:10,012 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:10,012 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_052.mp4

2025-04-08 09:58:12,503 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 83%|████████▎ | 45/54 [05:40<01:07,  7.50s/it]2025-04-08 09:58:16,238 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:16,239 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:16,239 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_024.mp4

2025-04-08 09:58:20,005 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 85%|████████▌ | 46/54 [05:49<01:02,  7.81s/it]2025-04-08 09:58:24,766 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:24,766 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:24,767 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_054.mp4

2025-04-08 09:58:29,335 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 87%|████████▋ | 47/54 [05:56<00:53,  7.67s/it]2025-04-08 09:58:32,095 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:32,096 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:32,096 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_013.mp4

2025-04-08 09:58:35,156 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 89%|████████▉ | 48/54 [06:01<00:41,  6.90s/it]2025-04-08 09:58:37,206 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:37,207 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:37,207 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_037.mp4

2025-04-08 09:58:45,096 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 91%|█████████ | 49/54 [06:11<00:37,  7.58s/it]2025-04-08 09:58:46,385 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:46,385 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:46,386 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_009.mp4

2025-04-08 09:58:49,582 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 93%|█████████▎| 50/54 [06:16<00:27,  6.87s/it]2025-04-08 09:58:51,603 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:51,604 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:51,604 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_029.mp4

2025-04-08 09:58:53,984 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 94%|█████████▍| 51/54 [06:21<00:18,  6.32s/it]2025-04-08 09:58:56,627 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:58:56,628 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:58:56,628 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_004.mp4

2025-04-08 09:59:00,493 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 96%|█████████▋| 52/54 [06:27<00:12,  6.41s/it]2025-04-08 09:59:03,262 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:03,262 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:03,263 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_042.mp4

2025-04-08 09:59:05,703 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 98%|█████████▊| 53/54 [06:32<00:05,  5.98s/it]2025-04-08 09:59:08,244 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:08,245 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:08,246 - INFO - AFC remote call 1 is done.

Start process: safe_video_investment_016.mp4

2025-04-08 09:59:10,620 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

100%|██████████| 54/54 [06:37<00:00,  7.37s/it]
  5%|▌         | 1/19 [06:37<1:59:22, 397.89s/it]

promotion

  0%|          | 0/63 [00:00<?, ?it/s]2025-04-08 09:59:13,251 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:13,252 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:13,252 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_036.mp4

2025-04-08 09:59:15,008 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  2%|▏         | 1/63 [00:04<04:28,  4.33s/it]2025-04-08 09:59:17,590 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:17,590 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:17,590 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_011.mp4

2025-04-08 09:59:21,261 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  3%|▎         | 2/63 [00:10<05:38,  5.56s/it]2025-04-08 09:59:24,001 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:24,001 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:24,002 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_025.mp4

2025-04-08 09:59:26,213 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  5%|▍         | 3/63 [00:15<05:01,  5.03s/it]2025-04-08 09:59:28,405 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:28,405 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:28,406 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_049.mp4

2025-04-08 09:59:30,265 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  6%|▋         | 4/63 [00:19<04:29,  4.57s/it]2025-04-08 09:59:32,273 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:32,274 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:32,274 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_004.mp4

2025-04-08 09:59:34,977 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  8%|▊         | 5/63 [00:23<04:28,  4.62s/it]2025-04-08 09:59:36,992 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:36,993 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:36,994 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_029.mp4

2025-04-08 09:59:40,000 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 10%|▉         | 6/63 [00:28<04:35,  4.84s/it]2025-04-08 09:59:42,252 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:42,253 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:42,253 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_018.mp4

2025-04-08 09:59:46,232 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 11%|█         | 7/63 [00:38<05:51,  6.28s/it]2025-04-08 09:59:51,495 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:51,496 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:51,496 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_017.mp4

2025-04-08 09:59:53,080 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
2025-04-08 09:59:56,445 - ERROR - Error decoding JSON.
Traceback (most recent call last):
  File "/var/tmp/ipykernel_4508/1988130805.py", line 123, in generate
    json_response = json.loads(clean_text)
  File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 13 column 1 (char 262)
2025-04-08 09:59:56,449 - WARNING - An error occurred: Extra data: line 13 column 1 (char 262). Retrying in 1 seconds...
2025-04-08 09:59:57,451 - INFO - Attempting API call (retry 1/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 09:59:57,452 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 09:59:57,452 - INFO - AFC remote call 1 is done.
2025-04-08 09:59:58,445 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 13%|█▎        | 8/63 [00:47<06:33,  7.15s/it]2025-04-08 10:00:00,494 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:00,495 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:00,496 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_052.mp4

2025-04-08 10:00:02,978 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 14%|█▍        | 9/63 [00:52<05:56,  6.60s/it]2025-04-08 10:00:05,880 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:05,881 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:05,881 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_045.mp4

2025-04-08 10:00:09,147 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 16%|█▌        | 10/63 [00:57<05:25,  6.15s/it]2025-04-08 10:00:11,030 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:11,031 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:11,031 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_012.mp4

2025-04-08 10:00:13,805 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 17%|█▋        | 11/63 [01:03<05:05,  5.87s/it]2025-04-08 10:00:16,261 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:16,261 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:16,262 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_016.mp4

2025-04-08 10:00:18,324 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 19%|█▉        | 12/63 [01:07<04:36,  5.41s/it]2025-04-08 10:00:20,632 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:20,633 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:20,633 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_030.mp4

2025-04-08 10:00:24,543 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 21%|██        | 13/63 [01:13<04:41,  5.64s/it]2025-04-08 10:00:26,782 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:26,783 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:26,783 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_044.mp4

2025-04-08 10:00:30,645 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 22%|██▏       | 14/63 [01:20<04:53,  5.99s/it]2025-04-08 10:00:33,595 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:33,595 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:33,596 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_002.mp4

2025-04-08 10:00:35,681 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 24%|██▍       | 15/63 [01:24<04:20,  5.43s/it]2025-04-08 10:00:37,714 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:37,714 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:37,715 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_034.mp4

2025-04-08 10:00:41,954 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 25%|██▌       | 16/63 [01:30<04:30,  5.76s/it]2025-04-08 10:00:44,233 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:44,233 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:44,234 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_039.mp4

2025-04-08 10:00:48,079 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 27%|██▋       | 17/63 [01:36<04:21,  5.68s/it]2025-04-08 10:00:49,731 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:49,731 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:49,732 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_033.mp4

2025-04-08 10:00:52,856 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 29%|██▊       | 18/63 [01:42<04:15,  5.67s/it]2025-04-08 10:00:55,374 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:00:55,375 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:00:55,376 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_060.mp4

2025-04-08 10:00:59,215 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 30%|███       | 19/63 [01:48<04:17,  5.86s/it]2025-04-08 10:01:01,687 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:01,688 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:01,688 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_055.mp4

2025-04-08 10:01:04,439 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 32%|███▏      | 20/63 [01:53<04:03,  5.66s/it]2025-04-08 10:01:06,893 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:06,893 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:06,894 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_043.mp4

2025-04-08 10:01:11,445 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 33%|███▎      | 21/63 [02:00<04:13,  6.04s/it]2025-04-08 10:01:13,815 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:13,815 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:13,816 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_046.mp4

2025-04-08 10:01:19,083 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 35%|███▍      | 22/63 [02:08<04:30,  6.60s/it]2025-04-08 10:01:21,724 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:21,724 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:21,725 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_054.mp4

2025-04-08 10:01:25,546 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 37%|███▋      | 23/63 [02:15<04:28,  6.72s/it]2025-04-08 10:01:28,709 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:28,710 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:28,710 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_007.mp4

2025-04-08 10:01:30,736 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
2025-04-08 10:01:34,364 - ERROR - Error decoding JSON.
Traceback (most recent call last):
  File "/var/tmp/ipykernel_4508/1988130805.py", line 123, in generate
    json_response = json.loads(clean_text)
  File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 13 column 1 (char 262)
2025-04-08 10:01:34,365 - WARNING - An error occurred: Extra data: line 13 column 1 (char 262). Retrying in 1 seconds...
2025-04-08 10:01:35,367 - INFO - Attempting API call (retry 1/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:35,367 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:35,368 - INFO - AFC remote call 1 is done.
2025-04-08 10:01:36,877 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 38%|███▊      | 24/63 [02:29<05:52,  9.04s/it]2025-04-08 10:01:43,185 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:43,185 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:43,186 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_023.mp4

2025-04-08 10:01:47,443 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 40%|███▉      | 25/63 [02:36<05:12,  8.23s/it]2025-04-08 10:01:49,520 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:49,520 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:49,521 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_056.mp4

2025-04-08 10:01:54,003 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 41%|████▏     | 26/63 [02:43<04:52,  7.90s/it]2025-04-08 10:01:56,626 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:56,626 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:56,627 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_042.mp4

2025-04-08 10:01:57,581 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 43%|████▎     | 27/63 [02:45<03:45,  6.26s/it]2025-04-08 10:01:59,087 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:01:59,088 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:01:59,088 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_050.mp4

2025-04-08 10:02:01,438 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 44%|████▍     | 28/63 [02:50<03:23,  5.81s/it]2025-04-08 10:02:03,829 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:03,830 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:03,830 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_053.mp4

2025-04-08 10:02:06,136 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 46%|████▌     | 29/63 [02:56<03:17,  5.81s/it]2025-04-08 10:02:09,648 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:09,649 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:09,650 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_028.mp4

2025-04-08 10:02:13,041 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 48%|████▊     | 30/63 [03:02<03:12,  5.82s/it]2025-04-08 10:02:15,487 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:15,487 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:15,488 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_009.mp4

2025-04-08 10:02:19,326 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 49%|████▉     | 31/63 [03:09<03:16,  6.13s/it]2025-04-08 10:02:22,361 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:22,362 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:22,362 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_051.mp4

2025-04-08 10:02:27,215 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 51%|█████     | 32/63 [03:16<03:18,  6.42s/it]2025-04-08 10:02:29,437 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:29,438 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:29,438 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_059.mp4

2025-04-08 10:02:33,144 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 52%|█████▏    | 33/63 [03:22<03:07,  6.27s/it]2025-04-08 10:02:35,347 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:35,347 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:35,348 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_001.mp4

2025-04-08 10:02:38,236 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 54%|█████▍    | 34/63 [03:27<02:52,  5.93s/it]2025-04-08 10:02:40,504 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:40,505 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:40,505 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_024.mp4

2025-04-08 10:02:42,808 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 56%|█████▌    | 35/63 [03:32<02:38,  5.68s/it]2025-04-08 10:02:45,583 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:45,584 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:45,584 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_031.mp4

2025-04-08 10:02:47,626 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 57%|█████▋    | 36/63 [03:36<02:23,  5.30s/it]2025-04-08 10:02:49,993 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:49,993 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:49,994 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_008.mp4

2025-04-08 10:02:53,125 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 59%|█████▊    | 37/63 [03:42<02:20,  5.40s/it]2025-04-08 10:02:55,629 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:02:55,630 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:02:55,630 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_063.mp4

2025-04-08 10:02:59,932 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 60%|██████    | 38/63 [03:49<02:24,  5.77s/it]2025-04-08 10:03:02,274 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:02,275 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:02,276 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_040.mp4

2025-04-08 10:03:06,295 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 62%|██████▏   | 39/63 [03:58<02:44,  6.86s/it]2025-04-08 10:03:11,671 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:11,671 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:11,671 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_061.mp4

2025-04-08 10:03:18,397 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 63%|██████▎   | 40/63 [04:06<02:48,  7.35s/it]2025-04-08 10:03:20,148 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:20,148 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:20,149 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_003.mp4

2025-04-08 10:03:25,127 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 65%|██████▌   | 41/63 [04:14<02:42,  7.40s/it]2025-04-08 10:03:27,684 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:27,685 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:27,685 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_022.mp4

2025-04-08 10:03:30,064 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 67%|██████▋   | 42/63 [04:19<02:19,  6.67s/it]2025-04-08 10:03:32,630 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:32,631 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:32,632 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_032.mp4

2025-04-08 10:03:34,595 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 68%|██████▊   | 43/63 [04:29<02:32,  7.61s/it]2025-04-08 10:03:42,438 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:42,438 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:42,439 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_062.mp4

2025-04-08 10:03:45,307 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 70%|██████▉   | 44/63 [04:34<02:13,  7.01s/it]2025-04-08 10:03:48,053 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:48,054 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:48,054 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_013.mp4

2025-04-08 10:03:50,216 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 71%|███████▏  | 45/63 [04:39<01:53,  6.28s/it]2025-04-08 10:03:52,645 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:52,645 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:52,646 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_047.mp4

2025-04-08 10:03:56,820 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 73%|███████▎  | 46/63 [04:46<01:48,  6.40s/it]2025-04-08 10:03:59,317 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:03:59,318 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:03:59,319 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_005.mp4

2025-04-08 10:04:02,400 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 75%|███████▍  | 47/63 [04:51<01:36,  6.03s/it]2025-04-08 10:04:04,489 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:04,490 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:04,490 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_037.mp4

2025-04-08 10:04:07,056 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 76%|███████▌  | 48/63 [04:55<01:24,  5.64s/it]2025-04-08 10:04:09,224 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:09,224 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:09,225 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_010.mp4

2025-04-08 10:04:13,678 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 78%|███████▊  | 49/63 [05:03<01:24,  6.06s/it]2025-04-08 10:04:16,265 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:16,265 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:16,266 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_041.mp4

2025-04-08 10:04:18,649 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 79%|███████▉  | 50/63 [05:08<01:15,  5.78s/it]2025-04-08 10:04:21,396 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:21,396 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:21,397 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_014.mp4

2025-04-08 10:04:23,411 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 81%|████████  | 51/63 [05:12<01:05,  5.49s/it]2025-04-08 10:04:26,201 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:26,202 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:26,202 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_006.mp4

2025-04-08 10:04:29,506 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 83%|████████▎ | 52/63 [05:19<01:05,  5.92s/it]2025-04-08 10:04:33,130 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:33,130 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:33,131 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_021.mp4

2025-04-08 10:04:40,696 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 84%|████████▍ | 53/63 [05:29<01:11,  7.16s/it]2025-04-08 10:04:43,184 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:43,184 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:43,185 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_048.mp4

2025-04-08 10:04:47,277 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 86%|████████▌ | 54/63 [05:36<01:02,  6.93s/it]2025-04-08 10:04:49,573 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:49,574 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:49,574 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_058.mp4

2025-04-08 10:04:53,262 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 87%|████████▋ | 55/63 [05:42<00:53,  6.66s/it]2025-04-08 10:04:55,614 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:04:55,614 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:04:55,615 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_057.mp4

2025-04-08 10:04:58,084 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 89%|████████▉ | 56/63 [05:47<00:43,  6.20s/it]2025-04-08 10:05:00,744 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:00,745 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:00,745 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_038.mp4

2025-04-08 10:05:02,238 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 90%|█████████ | 57/63 [05:51<00:32,  5.47s/it]2025-04-08 10:05:04,497 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:04,497 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:04,498 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_026.mp4

2025-04-08 10:05:08,050 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 92%|█████████▏| 58/63 [05:57<00:28,  5.63s/it]2025-04-08 10:05:10,502 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:10,503 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:10,503 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_020.mp4

2025-04-08 10:05:14,717 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 94%|█████████▎| 59/63 [06:03<00:23,  5.92s/it]2025-04-08 10:05:17,105 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:17,105 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:17,106 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_019.mp4

2025-04-08 10:05:19,733 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 95%|█████████▌| 60/63 [06:08<00:16,  5.64s/it]2025-04-08 10:05:22,088 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:22,088 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:22,089 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_015.mp4

2025-04-08 10:05:25,493 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 97%|█████████▋| 61/63 [06:14<00:11,  5.74s/it]2025-04-08 10:05:28,064 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:28,064 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:28,065 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_035.mp4

2025-04-08 10:05:30,436 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 98%|█████████▊| 62/63 [06:19<00:05,  5.43s/it]2025-04-08 10:05:32,772 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:32,773 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:32,773 - INFO - AFC remote call 1 is done.

Start process: safe_video_promotion_027.mp4

2025-04-08 10:05:35,117 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

100%|██████████| 63/63 [06:24<00:00,  6.11s/it]
 42%|████▏     | 8/19 [13:02<15:47, 86.15s/it]

sport

  0%|          | 0/20 [00:00<?, ?it/s]2025-04-08 10:05:38,054 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:38,055 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:38,055 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_012.mp4

2025-04-08 10:05:42,969 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  5%|▌         | 1/20 [00:08<02:50,  8.95s/it]2025-04-08 10:05:47,004 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:47,004 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:47,005 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_002.mp4

2025-04-08 10:05:49,335 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 10%|█         | 2/20 [00:13<01:55,  6.41s/it]2025-04-08 10:05:51,630 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:51,630 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:51,631 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_004.mp4

2025-04-08 10:05:54,297 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 15%|█▌        | 3/20 [00:19<01:48,  6.36s/it]2025-04-08 10:05:57,929 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:05:57,929 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:05:57,930 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_010.mp4

2025-04-08 10:06:01,117 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 20%|██        | 4/20 [00:24<01:32,  5.76s/it]2025-04-08 10:06:02,774 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:02,775 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:02,775 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_015.mp4

2025-04-08 10:06:06,405 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 25%|██▌       | 5/20 [00:30<01:27,  5.80s/it]2025-04-08 10:06:08,659 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:08,660 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:08,660 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_007.mp4

2025-04-08 10:06:12,566 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 30%|███       | 6/20 [00:36<01:21,  5.84s/it]2025-04-08 10:06:14,562 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:14,562 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:14,563 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_019.mp4

2025-04-08 10:06:17,599 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 35%|███▌      | 7/20 [00:41<01:13,  5.63s/it]2025-04-08 10:06:19,758 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:19,759 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:19,759 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_011.mp4

2025-04-08 10:06:21,706 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 40%|████      | 8/20 [00:45<01:01,  5.12s/it]2025-04-08 10:06:23,803 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:23,803 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:23,804 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_005.mp4

2025-04-08 10:06:29,115 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 45%|████▌     | 9/20 [00:53<01:04,  5.83s/it]2025-04-08 10:06:31,168 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:31,168 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:31,169 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_009.mp4

2025-04-08 10:06:33,655 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 50%|█████     | 10/20 [00:58<00:55,  5.55s/it]2025-04-08 10:06:36,109 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:36,109 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:36,110 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_014.mp4

2025-04-08 10:06:38,326 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 55%|█████▌    | 11/20 [01:03<00:50,  5.65s/it]2025-04-08 10:06:41,971 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:41,972 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:41,973 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_003.mp4

2025-04-08 10:06:45,631 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 60%|██████    | 12/20 [01:10<00:47,  5.88s/it]2025-04-08 10:06:48,385 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:48,385 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:48,386 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_020.mp4

2025-04-08 10:06:51,069 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 65%|██████▌   | 13/20 [01:15<00:39,  5.59s/it]2025-04-08 10:06:53,299 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:53,300 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:53,300 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_001.mp4

2025-04-08 10:06:56,125 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 70%|███████   | 14/20 [01:20<00:32,  5.35s/it]2025-04-08 10:06:58,099 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:06:58,100 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:06:58,100 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_006.mp4

2025-04-08 10:07:00,974 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 75%|███████▌  | 15/20 [01:26<00:28,  5.60s/it]2025-04-08 10:07:04,291 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:04,292 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:04,292 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_018.mp4

2025-04-08 10:07:07,996 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 80%|████████  | 16/20 [01:33<00:24,  6.09s/it]2025-04-08 10:07:11,521 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:11,522 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:11,523 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_017.mp4

2025-04-08 10:07:14,341 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 85%|████████▌ | 17/20 [01:38<00:17,  5.86s/it]2025-04-08 10:07:16,829 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:16,829 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:16,830 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_013.mp4

2025-04-08 10:07:18,968 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 90%|█████████ | 18/20 [01:46<00:12,  6.45s/it]2025-04-08 10:07:24,663 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:24,663 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:24,664 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_016.mp4

2025-04-08 10:07:27,864 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 95%|█████████▌| 19/20 [01:52<00:06,  6.16s/it]2025-04-08 10:07:30,149 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:30,150 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:30,150 - INFO - AFC remote call 1 is done.

Start process: safe_video_sport_008.mp4

2025-04-08 10:07:32,846 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

100%|██████████| 20/20 [01:57<00:00,  5.85s/it]
 53%|█████▎    | 10/19 [14:59<11:48, 78.67s/it]

comedy

  0%|          | 0/24 [00:00<?, ?it/s]2025-04-08 10:07:35,123 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:35,123 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:35,123 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_021.mp4

2025-04-08 10:07:37,674 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  4%|▍         | 1/24 [00:05<01:59,  5.20s/it]2025-04-08 10:07:40,325 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:40,326 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:40,326 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_011.mp4

2025-04-08 10:07:42,117 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  8%|▊         | 2/24 [00:09<01:36,  4.40s/it]2025-04-08 10:07:44,160 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:44,160 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:44,161 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_016.mp4

2025-04-08 10:07:46,469 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 12%|█▎        | 3/24 [00:13<01:32,  4.39s/it]2025-04-08 10:07:48,540 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:48,541 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:48,541 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_005.mp4

2025-04-08 10:07:51,733 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 17%|█▋        | 4/24 [00:19<01:38,  4.91s/it]2025-04-08 10:07:54,247 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:54,247 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:54,247 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_013.mp4

2025-04-08 10:07:56,948 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 21%|██        | 5/24 [00:24<01:33,  4.95s/it]2025-04-08 10:07:59,259 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:07:59,260 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:07:59,260 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_004.mp4

2025-04-08 10:08:01,656 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 25%|██▌       | 6/24 [00:29<01:28,  4.94s/it]2025-04-08 10:08:04,187 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:04,188 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:04,188 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_014.mp4

2025-04-08 10:08:06,632 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 29%|██▉       | 7/24 [00:34<01:29,  5.24s/it]2025-04-08 10:08:10,039 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:10,040 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:10,040 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_009.mp4

2025-04-08 10:08:12,606 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 33%|███▎      | 8/24 [00:40<01:25,  5.33s/it]2025-04-08 10:08:15,577 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:15,578 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:15,578 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_018.mp4

2025-04-08 10:08:17,586 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 38%|███▊      | 9/24 [00:44<01:15,  5.04s/it]2025-04-08 10:08:19,961 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:19,962 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:19,963 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_007.mp4

2025-04-08 10:08:22,263 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 42%|████▏     | 10/24 [00:49<01:09,  4.96s/it]2025-04-08 10:08:24,754 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:24,755 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:24,755 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_002.mp4

2025-04-08 10:08:27,185 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 46%|████▌     | 11/24 [00:54<01:02,  4.83s/it]2025-04-08 10:08:29,302 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:29,303 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:29,303 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_020.mp4

2025-04-08 10:08:31,864 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 50%|█████     | 12/24 [00:58<00:57,  4.83s/it]2025-04-08 10:08:34,105 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:34,105 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:34,106 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_001.mp4

2025-04-08 10:08:36,127 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 54%|█████▍    | 13/24 [01:03<00:52,  4.76s/it]2025-04-08 10:08:38,708 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:38,708 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:38,709 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_023.mp4

2025-04-08 10:08:41,551 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 58%|█████▊    | 14/24 [01:08<00:49,  4.94s/it]2025-04-08 10:08:44,063 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:44,063 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:44,063 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_012.mp4

2025-04-08 10:08:46,735 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 62%|██████▎   | 15/24 [01:14<00:45,  5.01s/it]2025-04-08 10:08:49,254 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:49,255 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:49,255 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_015.mp4

2025-04-08 10:08:51,920 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 67%|██████▋   | 16/24 [01:19<00:41,  5.24s/it]2025-04-08 10:08:55,008 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:08:55,009 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:08:55,010 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_022.mp4

2025-04-08 10:08:58,022 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 71%|███████   | 17/24 [01:25<00:37,  5.29s/it]2025-04-08 10:09:00,432 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:00,433 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:00,433 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_003.mp4

2025-04-08 10:09:02,884 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 75%|███████▌  | 18/24 [01:33<00:36,  6.15s/it]2025-04-08 10:09:08,567 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:08,568 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:08,568 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_006.mp4

2025-04-08 10:09:10,780 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 79%|███████▉  | 19/24 [01:37<00:28,  5.66s/it]2025-04-08 10:09:13,104 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:13,104 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:13,105 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_024.mp4

2025-04-08 10:09:15,168 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 83%|████████▎ | 20/24 [01:42<00:21,  5.32s/it]2025-04-08 10:09:17,635 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:17,635 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:17,636 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_010.mp4

2025-04-08 10:09:19,982 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 88%|████████▊ | 21/24 [01:47<00:15,  5.31s/it]2025-04-08 10:09:22,922 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:22,923 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:22,923 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_019.mp4

2025-04-08 10:09:25,724 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 92%|█████████▏| 22/24 [01:52<00:10,  5.21s/it]2025-04-08 10:09:27,893 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:27,894 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:27,894 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_008.mp4

2025-04-08 10:09:30,364 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 96%|█████████▌| 23/24 [01:56<00:04,  4.82s/it]2025-04-08 10:09:31,814 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:31,815 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:31,815 - INFO - AFC remote call 1 is done.

Start process: safe_video_comedy_017.mp4

2025-04-08 10:09:34,029 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

100%|██████████| 24/24 [02:01<00:00,  5.04s/it]
 84%|████████▍ | 16/19 [17:00<02:21, 47.26s/it]

charity

  0%|          | 0/42 [00:00<?, ?it/s]2025-04-08 10:09:36,141 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:36,141 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:36,142 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_032.mp4

2025-04-08 10:09:40,798 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  2%|▏         | 1/42 [00:06<04:34,  6.70s/it]2025-04-08 10:09:42,845 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:42,845 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:42,846 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_003.mp4

2025-04-08 10:09:45,503 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  5%|▍         | 2/42 [00:12<04:15,  6.39s/it]2025-04-08 10:09:49,009 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:49,010 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:49,010 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_008.mp4

2025-04-08 10:09:52,597 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  7%|▋         | 3/42 [00:18<04:04,  6.27s/it]2025-04-08 10:09:55,135 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:09:55,136 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:09:55,136 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_009.mp4

2025-04-08 10:09:58,415 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 10%|▉         | 4/42 [00:24<03:47,  5.99s/it]2025-04-08 10:10:00,697 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:00,698 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:00,698 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_023.mp4

2025-04-08 10:10:05,169 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 12%|█▏        | 5/42 [00:31<03:52,  6.29s/it]2025-04-08 10:10:07,519 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:07,520 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:07,520 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_005.mp4

2025-04-08 10:10:09,643 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 14%|█▍        | 6/42 [00:39<04:09,  6.94s/it]2025-04-08 10:10:15,728 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:15,728 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:15,729 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_006.mp4

2025-04-08 10:10:20,299 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 17%|█▋        | 7/42 [00:46<04:06,  7.04s/it]2025-04-08 10:10:22,966 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:22,967 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:22,967 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_013.mp4

2025-04-08 10:10:26,479 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 19%|█▉        | 8/42 [00:52<03:46,  6.66s/it]2025-04-08 10:10:28,805 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:28,806 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:28,806 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_016.mp4

2025-04-08 10:10:32,790 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 21%|██▏       | 9/42 [00:59<03:39,  6.66s/it]2025-04-08 10:10:35,461 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:35,462 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:35,462 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_004.mp4

2025-04-08 10:10:41,816 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 24%|██▍       | 10/42 [01:07<03:46,  7.06s/it]2025-04-08 10:10:43,433 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:43,433 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:43,434 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_002.mp4

2025-04-08 10:10:47,148 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 26%|██▌       | 11/42 [01:13<03:33,  6.88s/it]2025-04-08 10:10:49,887 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:49,888 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:49,888 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_029.mp4

2025-04-08 10:10:53,794 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 29%|██▊       | 12/42 [01:20<03:27,  6.90s/it]2025-04-08 10:10:56,843 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:10:56,844 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:10:56,844 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_035.mp4

2025-04-08 10:10:59,168 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 31%|███       | 13/42 [01:27<03:21,  6.93s/it]2025-04-08 10:11:03,856 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:03,857 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:03,857 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_001.mp4

2025-04-08 10:11:08,110 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 33%|███▎      | 14/42 [01:34<03:09,  6.76s/it]2025-04-08 10:11:10,212 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:10,212 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:10,213 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_018.mp4

2025-04-08 10:11:13,924 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 36%|███▌      | 15/42 [01:40<02:58,  6.62s/it]2025-04-08 10:11:16,518 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:16,518 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:16,519 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_011.mp4

2025-04-08 10:11:20,562 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 38%|███▊      | 16/42 [01:46<02:51,  6.58s/it]2025-04-08 10:11:22,996 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:22,997 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:22,997 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_040.mp4

2025-04-08 10:11:27,113 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 40%|████      | 17/42 [01:53<02:45,  6.61s/it]2025-04-08 10:11:29,666 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:29,667 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:29,667 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_014.mp4

2025-04-08 10:11:31,756 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 43%|████▎     | 18/42 [02:00<02:39,  6.65s/it]2025-04-08 10:11:36,402 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:36,403 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:36,403 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_026.mp4

2025-04-08 10:11:39,768 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 45%|████▌     | 19/42 [02:05<02:23,  6.25s/it]2025-04-08 10:11:41,748 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:41,748 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:41,749 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_031.mp4

2025-04-08 10:11:46,103 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 48%|████▊     | 20/42 [02:12<02:23,  6.51s/it]2025-04-08 10:11:48,855 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:48,856 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:48,856 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_019.mp4

2025-04-08 10:11:51,150 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 50%|█████     | 21/42 [02:17<02:07,  6.08s/it]2025-04-08 10:11:53,920 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:53,920 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:53,921 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_017.mp4

2025-04-08 10:11:57,910 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 52%|█████▏    | 22/42 [02:23<01:57,  5.89s/it]2025-04-08 10:11:59,383 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:11:59,384 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:11:59,384 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_010.mp4

2025-04-08 10:12:04,315 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 55%|█████▍    | 23/42 [02:30<02:02,  6.45s/it]2025-04-08 10:12:07,131 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:07,132 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:07,133 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_025.mp4

2025-04-08 10:12:09,920 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 57%|█████▋    | 24/42 [02:36<01:50,  6.14s/it]2025-04-08 10:12:12,566 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:12,566 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:12,567 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_012.mp4

2025-04-08 10:12:17,273 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 60%|█████▉    | 25/42 [02:43<01:48,  6.38s/it]2025-04-08 10:12:19,479 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:19,480 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:19,481 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_015.mp4

2025-04-08 10:12:24,065 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 62%|██████▏   | 26/42 [02:50<01:43,  6.49s/it]2025-04-08 10:12:26,249 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:26,250 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:26,250 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_028.mp4

2025-04-08 10:12:29,057 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 64%|██████▍   | 27/42 [02:55<01:31,  6.11s/it]2025-04-08 10:12:31,458 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:31,458 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:31,459 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_021.mp4

2025-04-08 10:12:34,224 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 67%|██████▋   | 28/42 [03:00<01:22,  5.87s/it]2025-04-08 10:12:36,771 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:36,772 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:36,772 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_027.mp4

2025-04-08 10:12:39,760 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 69%|██████▉   | 29/42 [03:07<01:20,  6.17s/it]2025-04-08 10:12:43,632 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:43,633 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:43,633 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_030.mp4

2025-04-08 10:12:46,548 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 71%|███████▏  | 30/42 [03:12<01:10,  5.87s/it]2025-04-08 10:12:48,793 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:48,793 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:48,794 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_007.mp4

2025-04-08 10:12:51,302 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 74%|███████▍  | 31/42 [03:17<01:01,  5.56s/it]2025-04-08 10:12:53,648 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:53,648 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:53,649 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_042.mp4

2025-04-08 10:12:56,683 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 76%|███████▌  | 32/42 [03:23<00:57,  5.77s/it]2025-04-08 10:12:59,903 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:12:59,903 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:12:59,903 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_022.mp4

2025-04-08 10:13:04,048 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 79%|███████▊  | 33/42 [03:30<00:53,  5.97s/it]2025-04-08 10:13:06,350 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:06,351 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:06,351 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_020.mp4

2025-04-08 10:13:11,542 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 81%|████████  | 34/42 [03:37<00:51,  6.47s/it]2025-04-08 10:13:13,989 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:13,989 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:13,990 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_039.mp4

2025-04-08 10:13:18,194 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 83%|████████▎ | 35/42 [03:44<00:45,  6.48s/it]2025-04-08 10:13:20,498 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:20,499 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:20,499 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_037.mp4

2025-04-08 10:13:25,012 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 86%|████████▌ | 36/42 [03:50<00:38,  6.46s/it]2025-04-08 10:13:26,894 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:26,894 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:26,895 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_036.mp4

2025-04-08 10:13:30,625 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 88%|████████▊ | 37/42 [03:56<00:30,  6.14s/it]2025-04-08 10:13:32,296 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:32,297 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:32,297 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_024.mp4

2025-04-08 10:13:37,133 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 90%|█████████ | 38/42 [04:03<00:25,  6.43s/it]2025-04-08 10:13:39,398 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:39,398 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:39,399 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_034.mp4

2025-04-08 10:13:46,017 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 93%|█████████▎| 39/42 [04:11<00:21,  7.12s/it]2025-04-08 10:13:48,141 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:48,141 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:48,142 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_041.mp4

2025-04-08 10:13:55,021 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 95%|█████████▌| 40/42 [04:20<00:14,  7.40s/it]2025-04-08 10:13:56,194 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:13:56,195 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:13:56,195 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_038.mp4

2025-04-08 10:14:00,389 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 98%|█████████▊| 41/42 [04:27<00:07,  7.28s/it]2025-04-08 10:14:03,197 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 10:14:03,198 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 10:14:03,198 - INFO - AFC remote call 1 is done.

Start process: safe_video_charity_033.mp4

2025-04-08 10:14:06,825 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

100%|██████████| 42/42 [04:33<00:00,  6.51s/it]
100%|██████████| 19/19 [21:34<00:00, 68.11s/it]

In [ ]:
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

safe_video_target_time = {
    'video': [],
    'label': [],
    'start_time': [],
    'end_time': []
}

safe_video_path = "./data/datasets/DemoDataset/videos/safe_videos"
for video_type in tqdm.tqdm(os.listdir(safe_video_path)):
    if video_type in safe_vedio_exp_cat:
        logger.info(f"Processing video type: {video_type}")
        video_type_path = os.path.join(safe_video_path, video_type)
        for video in tqdm.tqdm(os.listdir(video_type_path)):
            logger.info(f"Start processing video: {video}")
            video_path = os.path.join(video_type_path, video)
            try:
                res = detector.run(video_path)
                if 'start_time' in res and 'end_time' in res:
                    safe_video_target_time['video'].append(video)
                    safe_video_target_time['label'].append('safe')
                    safe_video_target_time['start_time'].append(res.get('start_time'))
                    safe_video_target_time['end_time'].append(res.get('end_time'))
                else:
                    logger.warning(f"Missing 'start_time' or 'end_time' in res for video {video}")
                    logger.debug(f"res dictionary: {res}")  # 記錄 res 字典的內容
            except Exception as e:
                logger.error(f"Error processing video {video}: {e}")
                logger.exception(e)

output_file = "safe_video_results.json"
try:
    with open(output_file, "w") as f:
        json.dump(safe_video_target_time, f, indent=4)
    logger.info(f"Results saved to {output_file}")
except Exception as e:
    logger.error(f"Error saving results to {output_file}: {e}")
    logger.exception(e)

safe_video_target_time_df = pd.DataFrame.from_dict(safe_video_target_time)
print(safe_video_target_time_df.head())

  0%|          | 0/19 [00:00<?, ?it/s]2025-04-08 11:38:13,232 - INFO - Processing video type: investment

  0%|          | 0/54 [00:00<?, ?it/s]2025-04-08 11:38:13,234 - INFO - Start processing video: safe_video_investment_025.mp4
2025-04-08 11:38:13,236 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:13,236 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:13,237 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:15,547 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  2%|▏         | 1/54 [00:08<07:18,  8.27s/it]2025-04-08 11:38:21,510 - INFO - Start processing video: safe_video_investment_023.mp4
2025-04-08 11:38:21,514 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:21,515 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:21,515 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:25,132 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  4%|▎         | 2/54 [00:14<05:54,  6.82s/it]2025-04-08 11:38:27,316 - INFO - Start processing video: safe_video_investment_011.mp4
2025-04-08 11:38:27,318 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:27,319 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:27,319 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:29,501 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  6%|▌         | 3/54 [00:18<04:49,  5.67s/it]2025-04-08 11:38:31,617 - INFO - Start processing video: safe_video_investment_007.mp4
2025-04-08 11:38:31,621 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:31,621 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:31,622 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:36,033 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  7%|▋         | 4/54 [00:24<04:55,  5.91s/it]2025-04-08 11:38:37,903 - INFO - Start processing video: safe_video_investment_046.MP4
2025-04-08 11:38:37,905 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:37,906 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:37,907 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:40,236 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

  9%|▉         | 5/54 [00:29<04:27,  5.46s/it]2025-04-08 11:38:42,570 - INFO - Start processing video: safe_video_investment_021.mp4
2025-04-08 11:38:42,572 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:42,573 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:42,573 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:44,327 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 11%|█         | 6/54 [00:33<04:02,  5.05s/it]2025-04-08 11:38:46,822 - INFO - Start processing video: safe_video_investment_044.MP4
2025-04-08 11:38:46,827 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:46,827 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:46,828 - INFO - AFC remote call 1 is done.
2025-04-08 11:38:57,389 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 13%|█▎        | 7/54 [00:45<05:49,  7.44s/it]2025-04-08 11:38:59,177 - INFO - Start processing video: safe_video_investment_030.mp4
2025-04-08 11:38:59,181 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:38:59,182 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:38:59,182 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:02,422 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 15%|█▍        | 8/54 [00:52<05:27,  7.13s/it]2025-04-08 11:39:05,642 - INFO - Start processing video: safe_video_investment_008.mp4
2025-04-08 11:39:05,646 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:05,647 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:05,647 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:10,646 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 17%|█▋        | 9/54 [00:59<05:26,  7.25s/it]2025-04-08 11:39:13,165 - INFO - Start processing video: safe_video_investment_019.mp4
2025-04-08 11:39:13,170 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:13,171 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:13,171 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:19,362 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 19%|█▊        | 10/54 [01:07<05:17,  7.21s/it]2025-04-08 11:39:20,276 - INFO - Start processing video: safe_video_investment_012.mp4
2025-04-08 11:39:20,278 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:20,279 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:20,280 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:22,345 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 20%|██        | 11/54 [01:11<04:30,  6.30s/it]2025-04-08 11:39:24,520 - INFO - Start processing video: safe_video_investment_001.mp4
2025-04-08 11:39:24,525 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:24,526 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:24,526 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:29,418 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 22%|██▏       | 12/54 [01:17<04:18,  6.17s/it]2025-04-08 11:39:30,379 - INFO - Start processing video: safe_video_investment_039.mp4
2025-04-08 11:39:30,381 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:30,382 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:30,383 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:32,308 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 24%|██▍       | 13/54 [01:21<03:52,  5.67s/it]2025-04-08 11:39:34,890 - INFO - Start processing video: safe_video_investment_041.mp4
2025-04-08 11:39:34,895 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:34,895 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:34,896 - INFO - AFC remote call 1 is done.
2025-04-08 11:39:39,035 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"

 26%|██▌       | 14/54 [01:27<03:53,  5.85s/it]2025-04-08 11:39:41,166 - INFO - Start processing video: safe_video_investment_048.MP4
2025-04-08 11:39:41,169 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 11:39:41,170 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 11:39:41,171 - INFO - AFC remote call 1 is done.

In [80]:
len(safe_video_target_time['label'])

202

In [81]:
len(safe_video_target_time['start_time'])

202

In [82]:
len(safe_video_target_time['end_time'])

202

In [63]:
import pandas as pd

In [83]:
safe_video_target_time_df = pd.DataFrame.from_dict(safe_video_target_time)
safe_video_target_time_df.head()

                           video label  start_time  end_time
0  safe_video_investment_025.mp4  safe         0.0       5.0
1  safe_video_investment_023.mp4  safe        10.0      15.0
2  safe_video_investment_011.mp4  safe        34.0      39.0
3  safe_video_investment_007.mp4  safe       150.0     155.0
4  safe_video_investment_046.MP4  safe        34.0      39.0

In [84]:
safe_video_target_time_df.shape

(202, 4)

In [85]:
print(safe_video_target_time_df[safe_video_target_time_df['start_time'].isna()].shape)
safe_video_target_time_df[safe_video_target_time_df['start_time'].isna()]

(21, 4)

                             video label  start_time  end_time
15   safe_video_investment_047.MP4  safe         NaN       NaN
24   safe_video_investment_040.mp4  safe         NaN       NaN
26   safe_video_investment_036.mp4  safe         NaN       NaN
35   safe_video_investment_005.mp4  safe         NaN       NaN
50   safe_video_investment_029.mp4  safe         NaN       NaN
56    safe_video_promotion_025.mp4  safe         NaN       NaN
61    safe_video_promotion_017.mp4  safe         NaN       NaN
64    safe_video_promotion_012.mp4  safe         NaN       NaN
65    safe_video_promotion_016.mp4  safe         NaN       NaN
70    safe_video_promotion_039.mp4  safe         NaN       NaN
82    safe_video_promotion_053.mp4  safe         NaN       NaN
83    safe_video_promotion_028.mp4  safe         NaN       NaN
90    safe_video_promotion_008.mp4  safe         NaN       NaN
104   safe_video_promotion_014.mp4  safe         NaN       NaN
110   safe_video_promotion_038.mp4  safe         NaN       NaN
132       safe_video_sport_017.mp4  safe         NaN       NaN
137      safe_video_comedy_011.mp4  safe         NaN       NaN
138      safe_video_comedy_016.mp4  safe         NaN       NaN
141      safe_video_comedy_004.mp4  safe         NaN       NaN
144      safe_video_comedy_018.mp4  safe         NaN       NaN
161     safe_video_charity_003.mp4  safe         NaN       NaN

In [86]:
result_by_safe_video = {}

for i in range(len(safe_video_target_time["video"])):
    video_name = safe_video_target_time["video"][i]
    result_by_safe_video[video_name] = {
        "label": safe_video_target_time["label"][i],
        "start_time": safe_video_target_time["start_time"][i],
        "end_time": safe_video_target_time["end_time"][i],
    }

with open("result_by_safe_video_exp4.json", "w", encoding="utf-8") as f:
    json.dump(result_by_safe_video, f, indent=2, ensure_ascii=False)

In [40]:
scam_video_target_time = {}

scam_video_path = "./data/datasets/DemoDataset/videos/scam_videos"
for video in tqdm.tqdm(os.listdir(scam_video_path)):
    print('Start process:', video)
    video_path = os.path.join(scam_video_path, video)
    res = detector.run(video_path)
    scam_video_target_time.setdefault('video', []).append(video)
    scam_video_target_time.setdefault('label', []).append('scam')
    scam_video_target_time.setdefault('start_time', []).append(res['start_time'])
    scam_video_target_time.setdefault('end_time', []).append(res['end_time'])

  0%|          | 0/49 [00:00<?, ?it/s]

Start process: 47_Biden_InvestmentScam.mp4

  2%|▏         | 1/49 [00:06<04:55,  6.16s/it]

Start process: 51_Lee Hsien Loong_InvestmentScam.mp4

  4%|▍         | 2/49 [00:11<04:26,  5.67s/it]

Start process: 11_Elon_InvestmentScam.mp4

  6%|▌         | 3/49 [00:17<04:22,  5.71s/it]

Start process: 36_Australia_InvestmentScam.mp4

  8%|▊         | 4/49 [00:23<04:24,  5.87s/it]

Start process: 41_FakeNews_InvestmentScam.mp4

 10%|█         | 5/49 [00:28<04:07,  5.62s/it]

Start process: 21_Elon_InvestmentScam.mp4

 12%|█▏        | 6/49 [00:32<03:42,  5.17s/it]

Start process: 27_MartinLewis_Elon.mp4

 14%|█▍        | 7/49 [00:43<04:54,  7.01s/it]

Start process: 55_JenniferLopez__WeightLossScam.mp4

 16%|█▋        | 8/49 [00:51<04:58,  7.29s/it]

Start process: 39_FakeNews_InvestmentScam.mp4

 18%|█▊        | 9/49 [00:56<04:23,  6.59s/it]

Start process: 17_SelenaGomez_FakeGiveaway.mp4

 20%|██        | 10/49 [01:01<03:54,  6.01s/it]

Start process: 32_Trump_InvestmentScam.mp4

 22%|██▏       | 11/49 [01:07<03:51,  6.08s/it]

Start process: 42_FakeNews_InvestmentScam.mp4

 24%|██▍       | 12/49 [01:14<03:58,  6.44s/it]

Start process: 15_Mr.Beast_FakeGiveaway.mp4

 27%|██▋       | 13/49 [01:21<03:52,  6.45s/it]

Start process: 48_DwayneJohnson_InvestmentScam.mp4

 29%|██▊       | 14/49 [01:26<03:28,  5.96s/it]

Start process: 29_Anthony Albanese_InvestmentScam.mp4

 31%|███       | 15/49 [01:36<04:06,  7.26s/it]

Start process: 56_Elon_InvestmentScam.mp4

 33%|███▎      | 16/49 [01:42<03:48,  6.91s/it]

Start process: 08_Elon_Crypto Scam.mp4

 35%|███▍      | 17/49 [01:48<03:35,  6.73s/it]

Start process: 50_GordonRamsay_FakeGiveaway.mp4

 37%|███▋      | 18/49 [01:54<03:22,  6.54s/it]

Start process: 31_Trump_InvestmentScam.mp4

 39%|███▉      | 19/49 [01:59<02:59,  5.98s/it]

Start process: 10_Elon_Crypto Scam.mp4

 41%|████      | 20/49 [02:05<02:55,  6.06s/it]

Start process: 30_GayleKing_WeightLoss Scam.mp4

 43%|████▎     | 21/49 [02:11<02:43,  5.85s/it]

Start process: 35_Tracy Grimshaw_WeightLoss Scam.mp4

 45%|████▍     | 22/49 [02:16<02:34,  5.72s/it]

Start process: 53_Elon_Crypto Scam.mp4

 47%|████▋     | 23/49 [02:22<02:33,  5.89s/it]

Start process: 20_Elon_Crypto Scam.mp4

 49%|████▉     | 24/49 [02:27<02:18,  5.53s/it]

Start process: 14_Oprah_FakeGiveaway.mp4

 51%|█████     | 25/49 [02:33<02:18,  5.77s/it]

Start process: 28_BBCNews_Elon_InvestmentScam.mp4

 53%|█████▎    | 26/49 [02:44<02:44,  7.14s/it]

Start process: 44_FakeNews_InvestmentScam.mp4

 55%|█████▌    | 27/49 [02:50<02:32,  6.92s/it]

Start process: 19_Elon_Crypto Scam.mp4

 57%|█████▋    | 28/49 [02:55<02:11,  6.25s/it]

Start process: 13_JenniferAniston_FakeGiveaway.mp4

 59%|█████▉    | 29/49 [03:00<01:58,  5.91s/it]

Start process: 49_Mr.Beast_FakeAd.mp4

 61%|██████    | 30/49 [03:12<02:26,  7.71s/it]

Start process: 38_FakeNews_ScamApp.mp4

 63%|██████▎   | 31/49 [03:17<02:03,  6.84s/it]

Start process: 37_FakeNews_ScamApp.mp4

 65%|██████▌   | 32/49 [03:23<01:56,  6.84s/it]

Start process: 40_FakeNews_InvestmentScam.mp4

 67%|██████▋   | 33/49 [03:30<01:46,  6.65s/it]

Start process: 52_FakeApp_InvestmentScam.mp4

 69%|██████▉   | 34/49 [03:42<02:04,  8.30s/it]

Start process: 45_FakeNews_InvestmentScam.mp4

 71%|███████▏  | 35/49 [03:51<02:00,  8.62s/it]

Start process: 22_MichaelSaylor_CryptoScam.mp4

 73%|███████▎  | 36/49 [03:57<01:42,  7.91s/it]

Start process: 16_TaylorSwift_FakeGiveaway.mp4

 76%|███████▌  | 37/49 [04:05<01:32,  7.73s/it]

Start process: 04_Elon_Crypto Scam.mp4

 78%|███████▊  | 38/49 [04:09<01:14,  6.77s/it]

Start process: 57_Michael Saylor_Crypto Scam.mp4

 80%|███████▉  | 39/49 [04:16<01:07,  6.75s/it]

Start process: 25_Elon_Crypto Scam.mp4

 82%|████████▏ | 40/49 [04:24<01:03,  7.07s/it]

Start process: 54_Trump_Fake Ad.mp4

 84%|████████▎ | 41/49 [04:31<00:56,  7.02s/it]

Start process: 24_Elon_Trump_Crypto Scam.mp4

 86%|████████▌ | 42/49 [04:42<00:59,  8.43s/it]

Start process: 12_Elon_Crypto Scam.mp4

 88%|████████▊ | 43/49 [04:49<00:46,  7.76s/it]

Start process: 07_Elon_Crypto Scam.mp4

 90%|████████▉ | 44/49 [04:53<00:34,  6.81s/it]

Start process: 26_Ripple_Crypto Scam.mp4

 92%|█████████▏| 45/49 [04:58<00:24,  6.22s/it]

Start process: 46_KevinOLeary_InvestmentScam.mp4

 94%|█████████▍| 46/49 [05:04<00:18,  6.11s/it]

Start process: 09_TaylorSwif_FakeGiveaway.mp4

 96%|█████████▌| 47/49 [05:08<00:11,  5.63s/it]

Start process: 43_FakeNews_InvestmentScam.mp4

 98%|█████████▊| 48/49 [05:14<00:05,  5.46s/it]

Start process: 34_Anthony Albanese_InvestmentScam.mp4

100%|██████████| 49/49 [05:19<00:00,  6.53s/it]

In [89]:
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

scam_video_target_time = {
    'video': [],
    'label': [],
    'start_time': [],
    'end_time': []
}

scam_video_path = "./data/datasets/DemoDataset/videos/scam_videos"
for video in tqdm.tqdm(os.listdir(scam_video_path)):
    logger.info(f"Start processing video: {video}")
    video_path = os.path.join(scam_video_path, video)
    try:
        res = detector.run(video_path)
        if 'start_time' in res and 'end_time' in res:
            scam_video_target_time['video'].append(video)
            scam_video_target_time['label'].append('scam')
            scam_video_target_time['start_time'].append(res.get('start_time'))
            scam_video_target_time['end_time'].append(res.get('end_time'))
        else:
            logger.warning(f"Missing 'start_time' or 'end_time' in res for video {video}")
            logger.debug(f"res dictionary: {res}")  # 記錄 res 字典的內容
    except Exception as e:
        logger.error(f"Error processing video {video}: {e}")
        logger.exception(e)

  0%|          | 0/49 [00:00<?, ?it/s]2025-04-08 15:06:36,547 - INFO - Start processing video: 47_Biden_InvestmentScam.mp4
2025-04-08 15:06:36,549 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:06:36,549 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:06:36,550 - INFO - AFC remote call 1 is done.
2025-04-08 15:06:38,858 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
  2%|▏         | 1/49 [00:05<04:15,  5.33s/it]2025-04-08 15:06:41,877 - INFO - Start processing video: 51_Lee Hsien Loong_InvestmentScam.mp4
2025-04-08 15:06:41,879 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:06:41,880 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:06:41,880 - INFO - AFC remote call 1 is done.
2025-04-08 15:06:44,220 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
  4%|▍         | 2/49 [00:09<03:46,  4.81s/it]2025-04-08 15:06:46,325 - INFO - Start processing video: 11_Elon_InvestmentScam.mp4
2025-04-08 15:06:46,326 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:06:46,327 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:06:46,327 - INFO - AFC remote call 1 is done.
2025-04-08 15:06:48,537 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
  6%|▌         | 3/49 [00:14<03:43,  4.87s/it]2025-04-08 15:06:51,263 - INFO - Start processing video: 36_Australia_InvestmentScam.mp4
2025-04-08 15:06:51,265 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:06:51,266 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:06:51,266 - INFO - AFC remote call 1 is done.
2025-04-08 15:06:53,708 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
  8%|▊         | 4/49 [00:19<03:43,  4.98s/it]2025-04-08 15:06:56,403 - INFO - Start processing video: 41_FakeNews_InvestmentScam.mp4
2025-04-08 15:06:56,404 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:06:56,405 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:06:56,406 - INFO - AFC remote call 1 is done.
2025-04-08 15:06:58,801 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 10%|█         | 5/49 [00:24<03:33,  4.85s/it]2025-04-08 15:07:01,026 - INFO - Start processing video: 21_Elon_InvestmentScam.mp4
2025-04-08 15:07:01,027 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:01,028 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:01,028 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:02,897 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 12%|█▏        | 6/49 [00:28<03:20,  4.66s/it]2025-04-08 15:07:05,308 - INFO - Start processing video: 27_MartinLewis_Elon.mp4
2025-04-08 15:07:05,311 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:05,312 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:05,312 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:14,196 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 14%|█▍        | 7/49 [00:39<04:33,  6.52s/it]2025-04-08 15:07:15,651 - INFO - Start processing video: 55_JenniferLopez__WeightLossScam.mp4
2025-04-08 15:07:15,655 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:15,656 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:15,656 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:24,047 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 16%|█▋        | 8/49 [00:48<05:10,  7.58s/it]2025-04-08 15:07:25,512 - INFO - Start processing video: 39_FakeNews_InvestmentScam.mp4
2025-04-08 15:07:25,513 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:25,514 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:25,514 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:28,159 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 18%|█▊        | 9/49 [00:53<04:30,  6.77s/it]2025-04-08 15:07:30,490 - INFO - Start processing video: 17_SelenaGomez_FakeGiveaway.mp4
2025-04-08 15:07:30,492 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:30,493 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:30,493 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:32,670 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 20%|██        | 10/49 [01:00<04:20,  6.67s/it]2025-04-08 15:07:36,958 - INFO - Start processing video: 32_Trump_InvestmentScam.mp4
2025-04-08 15:07:36,960 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:36,960 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:36,961 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:40,057 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 22%|██▏       | 11/49 [01:05<03:58,  6.29s/it]2025-04-08 15:07:42,372 - INFO - Start processing video: 42_FakeNews_InvestmentScam.mp4
2025-04-08 15:07:42,373 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:42,374 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:42,374 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:45,077 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 24%|██▍       | 12/49 [01:11<03:44,  6.06s/it]2025-04-08 15:07:47,899 - INFO - Start processing video: 15_Mr.Beast_FakeGiveaway.mp4
2025-04-08 15:07:47,900 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:47,901 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:47,901 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:49,429 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 27%|██▋       | 13/49 [01:18<03:47,  6.33s/it]2025-04-08 15:07:54,861 - INFO - Start processing video: 48_DwayneJohnson_InvestmentScam.mp4
2025-04-08 15:07:54,863 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:54,864 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:54,864 - INFO - AFC remote call 1 is done.
2025-04-08 15:07:56,613 - INFO - HTTP Request: POST https://us-east1-aiplatform.googleapis.com/v1beta1/projects/deepfake-422901/locations/us-east1/publishers/google/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse "HTTP/1.1 200 OK"
 29%|██▊       | 14/49 [01:23<03:28,  5.96s/it]2025-04-08 15:07:59,969 - INFO - Start processing video: 29_Anthony Albanese_InvestmentScam.mp4
2025-04-08 15:07:59,973 - INFO - Attempting API call (retry 0/3). API Parameters: {'model': 'gemini-2.0-flash-001', 'temperature': 0.1, 'top_p': 0.95, 'max_output_tokens': 8192, 'safety_settings': [SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 'HARM_CATEGORY_HATE_SPEECH'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 'HARM_CATEGORY_DANGEROUS_CONTENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 'HARM_CATEGORY_SEXUALLY_EXPLICIT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>), SafetySetting(method=None, category=<HarmCategory.HARM_CATEGORY_HARASSMENT: 'HARM_CATEGORY_HARASSMENT'>, threshold=<HarmBlockThreshold.OFF: 'OFF'>)]}
2025-04-08 15:07:59,973 - INFO - AFC is enabled with max remote calls: 10.
2025-04-08 15:07:59,974 - INFO - AFC remote call 1 is done.

In [90]:
scam_video_target_time_df = pd.DataFrame.from_dict(scam_video_target_time)
scam_video_target_time_df.head()

                                   video label  start_time  end_time
0            47_Biden_InvestmentScam.mp4  scam         0.0       5.0
1  51_Lee Hsien Loong_InvestmentScam.mp4  scam        30.0      35.0
2             11_Elon_InvestmentScam.mp4  scam        28.0      33.0
3        36_Australia_InvestmentScam.mp4  scam         4.0       9.0
4         41_FakeNews_InvestmentScam.mp4  scam        22.0      27.0

In [91]:
scam_video_target_time_df[scam_video_target_time_df['start_time'].isna()]

                                  video label  start_time  end_time
13  48_DwayneJohnson_InvestmentScam.mp4  scam         NaN       NaN
16              08_Elon_Crypto Scam.mp4  scam         NaN       NaN
17     50_GordonRamsay_FakeGiveaway.mp4  scam         NaN       NaN
28  13_JenniferAniston_FakeGiveaway.mp4  scam         NaN       NaN
29               49_Mr.Beast_FakeAd.mp4  scam         NaN       NaN
31              37_FakeNews_ScamApp.mp4  scam         NaN       NaN
42              12_Elon_Crypto Scam.mp4  scam         NaN       NaN

In [112]:
scam_video_target_time_df[scam_video_target_time_df['start_time'].isna()]

                      video label  start_time  end_time
27  19_Elon_Crypto Scam.mp4  scam         NaN       NaN
37  04_Elon_Crypto Scam.mp4  scam         NaN       NaN

In [92]:
result_by_scam_video = {}

for i in range(len(scam_video_target_time["video"])):
    video_name = scam_video_target_time["video"][i]
    result_by_scam_video[video_name] = {
        "label": scam_video_target_time["label"][i],
        "start_time": scam_video_target_time["start_time"][i],
        "end_time": scam_video_target_time["end_time"][i],
    }

with open("result_by_scam_video_exp4.json", "w", encoding="utf-8") as f:
    json.dump(result_by_scam_video, f, indent=2, ensure_ascii=False)

In [113]:
video_target_time_df = pd.concat([safe_video_target_time_df, scam_video_target_time_df])

In [114]:
video_target_time_df.head()

                           video label  start_time  end_time
0  safe_video_investment_025.mp4  safe         3.0       8.0
1  safe_video_investment_023.mp4  safe        54.0      59.0
2  safe_video_investment_011.mp4  safe         0.0       5.0
3  safe_video_investment_007.mp4  safe         5.0      10.0
4  safe_video_investment_046.MP4  safe         0.0       5.0

In [115]:
video_target_time_df.to_csv('video_target_time_df.csv', index=False)

### Re-check

In [1]:
import pandas as pd

In [3]:
video_target_time_df = pd.read_csv('video_target_time_df.csv')
video_target_time_df.head()

                           video label  start_time  end_time
0  safe_video_investment_025.mp4  safe         3.0       8.0
1  safe_video_investment_023.mp4  safe        54.0      59.0
2  safe_video_investment_011.mp4  safe         0.0       5.0
3  safe_video_investment_007.mp4  safe         5.0      10.0
4  safe_video_investment_046.MP4  safe         0.0       5.0

In [4]:
video_target_time_df.shape

(571, 4)

In [6]:
video_target_time_df[video_target_time_df['start_time'].isna()]

                                    video label  start_time  end_time
62                safe_video_food_004.mp4  safe         NaN       NaN
63                safe_video_food_009.mp4  safe         NaN       NaN
64                safe_video_food_008.mp4  safe         NaN       NaN
65                safe_video_food_012.mp4  safe         NaN       NaN
84   safe_video_education_content_008.mp4  safe         NaN       NaN
..                                    ...   ...         ...       ...
474            safe_video_charity_017.mp4  safe         NaN       NaN
483            safe_video_charity_007.mp4  safe         NaN       NaN
486            safe_video_charity_020.mp4  safe         NaN       NaN
549               19_Elon_Crypto Scam.mp4  scam         NaN       NaN
559               04_Elon_Crypto Scam.mp4  scam         NaN       NaN

[64 rows x 4 columns]

In [7]:
video_target_time_df[video_target_time_df['end_time'].isna()]

                                    video label  start_time  end_time
62                safe_video_food_004.mp4  safe         NaN       NaN
63                safe_video_food_009.mp4  safe         NaN       NaN
64                safe_video_food_008.mp4  safe         NaN       NaN
65                safe_video_food_012.mp4  safe         NaN       NaN
84   safe_video_education_content_008.mp4  safe         NaN       NaN
..                                    ...   ...         ...       ...
474            safe_video_charity_017.mp4  safe         NaN       NaN
483            safe_video_charity_007.mp4  safe         NaN       NaN
486            safe_video_charity_020.mp4  safe         NaN       NaN
549               19_Elon_Crypto Scam.mp4  scam         NaN       NaN
559               04_Elon_Crypto Scam.mp4  scam         NaN       NaN

[64 rows x 4 columns]